In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train_part1 = pd.read_parquet("../data/train_part_1.parquet", engine='fastparquet')

Сравним с предыдущим набором

In [3]:
train_part1.info()

<class 'pandas.DataFrame'>
RangeIndex: 28618594 entries, 0 to 28618593
Data columns (total 23 columns):
 #   Column                      Dtype  
---  ------                      -----  
 0   customer_id                 int64  
 1   event_id                    int64  
 2   event_dttm                  object 
 3   event_type_nm               int32  
 4   event_desc                  int32  
 5   channel_indicator_type      int32  
 6   channel_indicator_sub_type  int32  
 7   operaton_amt                float64
 8   currency_iso_cd             float64
 9   mcc_code                    object 
 10  pos_cd                      float64
 11  accept_language             object 
 12  browser_language            object 
 13  timezone                    float64
 14  session_id                  float64
 15  operating_system_type       float64
 16  battery                     object 
 17  device_system_version       object 
 18  screen_size                 object 
 19  developer_tools             ob

In [4]:
train_part1.head(5)

,customer_id,event_id,event_dttm,event_type_nm,event_desc,channel_indicator_type,channel_indicator_sub_type,operaton_amt,currency_iso_cd,mcc_code,...,timezone,session_id,operating_system_type,battery,device_system_version,screen_size,developer_tools,phone_voip_call_state,web_rdp_connection,compromised
0,123123123123129,123999300382879,2024-10-01 05:29:14,14,75,6,5,56422.0,0.0,4,...,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None
1,123123123123129,124531875713936,2024-10-01 10:17:22,7,56,4,15,NaN,NaN,None,...,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None
2,123123123123129,123329285580171,2024-10-01 10:20:03,3,120,6,5,300870.0,0.0,10,...,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None
3,123123123123129,124334305430665,2024-10-02 07:48:09,14,75,6,5,298458.0,0.0,1,...,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None
4,123123123123129,126215501146513,2024-10-02 11:20:40,14,75,6,5,59944.0,0.0,15,...,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None


In [5]:
def most_popular(dataframe):            
    cols = dataframe.columns
    for i in cols:
        print(f"{i}:")
        print(f"{dataframe[i].mode(dropna=False)}\n")

In [6]:
most_popular(train_part1)

customer_id:
0    123166072796364
Name: customer_id, dtype: int64

event_id:
0           123123123123263
1           123123123126557
2           123123123126655
3           123123123126784
4           123123123127994
                 ...       
28618589    126550511519551
28618590    126550511523138
28618591    126550511525464
28618592    126550511527439
28618593    126550511527670
Name: event_id, Length: 28618594, dtype: int64

event_dttm:
0    2024-10-18 10:33:24
1    2024-12-27 12:47:12
2    2025-05-15 10:09:40
Name: event_dttm, dtype: object

event_type_nm:
0    7
Name: event_type_nm, dtype: int32

event_desc:
0    56
Name: event_desc, dtype: int32

channel_indicator_type:
0    4
Name: channel_indicator_type, dtype: int32

channel_indicator_sub_type:
0    15
Name: channel_indicator_sub_type, dtype: int32

operaton_amt:
0   NaN
Name: operaton_amt, dtype: float64

currency_iso_cd:
0    0.0
Name: currency_iso_cd, dtype: float64

mcc_code:
0    None
Name: mcc_code, dtype: object

pos_c

In [7]:
cols = train_part1.columns
for i in range(23):
    print(f"{train_part1[cols[i]].value_counts(dropna=False)}\n")

customer_id
123166072796364    3376
123277741949059    3056
123432360770994    3011
123286331880824    2877
123260562078628    2838
                   ... 
123140302997224      58
123174662734089      57
123329281556836      53
123449540641697      47
123475310445074      45
Name: count, Length: 33333, dtype: int64

event_id
123999300382879    1
124531875713936    1
123329285580171    1
124334305430665    1
126215501146513    1
                  ..
126490381958304    1
124128146411089    1
125433819853542    1
126215503301577    1
126052293072084    1
Name: count, Length: 28618594, dtype: int64

event_dttm
2024-10-18 10:33:24    14
2025-05-15 10:09:40    14
2024-12-27 12:47:12    14
2025-02-15 09:01:30    13
2024-12-02 11:08:00    13
                       ..
2025-05-10 12:46:56     1
2025-05-16 11:38:21     1
2025-05-17 02:59:25     1
2025-05-17 10:48:09     1
2025-05-25 09:16:59     1
Name: count, Length: 13374722, dtype: int64

event_type_nm
7     11945911
14    11657184
8      2076

In [8]:
train_part1.drop(columns=["event_dttm", "accept_language", "device_system_version", "browser_language", "screen_size", "battery"]).corr()

,customer_id,event_id,event_type_nm,event_desc,channel_indicator_type,channel_indicator_sub_type,operaton_amt,currency_iso_cd,mcc_code,pos_cd,timezone,session_id,operating_system_type,developer_tools,phone_voip_call_state,web_rdp_connection,compromised
customer_id,1.000000,0.000166,0.002786,0.000809,-0.002097,-0.001194,-0.001411,-0.001777,0.004853,0.005461,-0.010480,0.000149,-0.019038,-0.011441,-0.000049,0.020437,0.007298
event_id,0.000166,1.000000,-0.000229,0.000128,-0.000004,0.000138,-0.000555,-0.000053,0.000129,0.000355,0.000331,0.000538,-0.001012,0.000233,-0.000238,0.000362,0.000124
event_type_nm,0.002786,-0.000229,1.000000,0.072384,-0.524311,-0.356222,-0.002140,-0.026136,-0.103191,-0.192624,-0.011046,0.000113,-0.051402,-0.001656,0.000139,0.048211,-0.005155
event_desc,0.000809,0.000128,0.072384,1.000000,-0.467516,-0.336685,-0.000302,0.019911,0.014639,0.056774,-0.002135,0.000488,-0.002162,-0.000251,-0.000935,0.017924,-0.001660
channel_indicator_type,-0.002097,-0.000004,-0.524311,-0.467516,1.000000,0.741870,0.004310,-0.025096,0.001021,0.029392,0.000900,-0.000016,0.000010,0.002232,-0.000609,0.000094,0.000419
channel_indicator_sub_type,-0.001194,0.000138,-0.356222,-0.336685,0.741870,1.000000,0.009070,-0.021488,0.009561,0.160798,-0.001256,-0.000107,0.000956,0.002187,-0.000506,0.006183,0.000428
operaton_amt,-0.001411,-0.000555,-0.002140,-0.000302,0.004310,0.009070,1.000000,0.002833,0.023650,0.031784,0.002245,0.000264,-0.008470,0.002630,0.007196,0.002749,-0.000397
currency_iso_cd,-0.001777,-0.000053,-0.026136,0.019911,-0.025096,-0.021488,0.002833,1.000000,0.011713,0.001197,0.001195,0.000377,-0.002448,0.000664,0.003718,0.011448,-0.000335
mcc_code,0.004853,0.000129,-0.103191,0.014639,0.001021,0.009561,0.023650,0.011713,1.000000,-0.073881,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pos_cd,0.005461,0.000355,-0.192624,0.056774,0.029392,0.160798,0.031784,0.001197,-0.073881,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN


- *channel_indicator_type* и *channel_indicator_sub_type*

In [9]:
# delete = ["accept_language", "browser_language", "timezone", "session_id", "operating_system_type", \
#         "battery", "device_system_version", "screen_size"]

# train_part1.drop(columns=delete, inplace=True)

In [10]:
#########
train_part1.fillna(value=-1, inplace=True)
train_part1["phone_voip_call_state"] = train_part1["phone_voip_call_state"].astype(dtype="int16")
train_part1["web_rdp_connection"] = train_part1["web_rdp_connection"].astype(dtype="int16")

In [11]:
train_part1["Hour"] = pd.to_datetime(train_part1["event_dttm"]).dt.hour
train_part1.drop(columns="event_dttm", inplace=True)

#### Добавим таргет и преобразуем его

In [13]:
labels = pd.read_parquet("../data/train_labels.parquet", engine='fastparquet')

In [14]:
labels.head()

,customer_id,event_id,target
0,123123123123129,124093788813382,0
1,123123123123138,126035112904381,0
2,123123123123169,124325714018852,1
3,123123123123169,124944191029616,1
4,123123123123169,126395888234936,1


In [15]:
train_part1 = train_part1.merge(labels, how='left', on=['customer_id', 'event_id'])

In [16]:
train_part1["target"].value_counts(dropna=False)

target
NaN    28589128
1.0       17384
0.0       12082
Name: count, dtype: int64

In [17]:
###########
train_part1["target"] = train_part1["target"].fillna(0, inplace=True).astype(dtype="int16")

/tmp/ipykernel_11307/3661410496.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_part1["target"] = train_part1["target"].fillna(0, inplace=True).astype(dtype="int16")


In [18]:
train_part1

,customer_id,event_id,event_type_nm,event_desc,channel_indicator_type,channel_indicator_sub_type,operaton_amt,currency_iso_cd,mcc_code,pos_cd,...,operating_system_type,battery,device_system_version,screen_size,developer_tools,phone_voip_call_state,web_rdp_connection,compromised,Hour,target
0,123123123123129,123999300382879,14,75,6,5,56422.0,0.0,4,3.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,5,0
1,123123123123129,124531875713936,7,56,4,15,-1.0,-1.0,-1,-1.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,10,0
2,123123123123129,123329285580171,3,120,6,5,300870.0,0.0,10,3.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,10,0
3,123123123123129,124334305430665,14,75,6,5,298458.0,0.0,1,3.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,7,0
4,123123123123129,126215501146513,14,75,6,5,59944.0,0.0,15,3.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28618589,123501080247591,126490381958304,14,75,0,5,8067.0,0.0,4,-1.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,4,0
28618590,123501080247591,124128146411089,14,75,0,5,9005.0,0.0,4,-1.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,8,0
28618591,123501080247591,125433819853542,14,75,0,5,7992.0,0.0,4,-1.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,8,0
28618592,123501080247591,126215503301577,14,75,0,5,40849.0,0.0,4,-1.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,12,0


In [19]:
train_part1["target"].value_counts()

target
0    28601210
1       17384
Name: count, dtype: int64

In [20]:
train_part1.drop(columns=["customer_id", "event_id"], inplace=True)

In [21]:
train_part1

,event_type_nm,event_desc,channel_indicator_type,channel_indicator_sub_type,operaton_amt,currency_iso_cd,mcc_code,pos_cd,accept_language,browser_language,...,operating_system_type,battery,device_system_version,screen_size,developer_tools,phone_voip_call_state,web_rdp_connection,compromised,Hour,target
0,14,75,6,5,56422.0,0.0,4,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,5,0
1,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,10,0
2,3,120,6,5,300870.0,0.0,10,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,10,0
3,14,75,6,5,298458.0,0.0,1,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,7,0
4,14,75,6,5,59944.0,0.0,15,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28618589,14,75,0,5,8067.0,0.0,4,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,4,0
28618590,14,75,0,5,9005.0,0.0,4,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,8,0
28618591,14,75,0,5,7992.0,0.0,4,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,8,0
28618592,14,75,0,5,40849.0,0.0,4,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,12,0


In [22]:
train_part1["mcc_code"] = train_part1["mcc_code"].astype(dtype="int16")
train_part1["compromised"] = train_part1["compromised"].astype(dtype="int16")
train_part1["developer_tools"] = train_part1["developer_tools"].astype(dtype="int16")

In [23]:
train_part1.info()

<class 'pandas.DataFrame'>
RangeIndex: 28618594 entries, 0 to 28618593
Data columns (total 22 columns):
 #   Column                      Dtype  
---  ------                      -----  
 0   event_type_nm               int32  
 1   event_desc                  int32  
 2   channel_indicator_type      int32  
 3   channel_indicator_sub_type  int32  
 4   operaton_amt                float64
 5   currency_iso_cd             float64
 6   mcc_code                    int16  
 7   pos_cd                      float64
 8   accept_language             object 
 9   browser_language            object 
 10  timezone                    float64
 11  session_id                  float64
 12  operating_system_type       float64
 13  battery                     object 
 14  device_system_version       object 
 15  screen_size                 object 
 16  developer_tools             int16  
 17  phone_voip_call_state       int16  
 18  web_rdp_connection          int16  
 19  compromised                 in

Сравню некоторые ранее удаленные столбцы для классов 0 и 1

In [27]:
train_part1.loc[train_part1["target"] == 1].tail(25)

,event_type_nm,event_desc,channel_indicator_type,channel_indicator_sub_type,operaton_amt,currency_iso_cd,mcc_code,pos_cd,accept_language,browser_language,...,operating_system_type,battery,device_system_version,screen_size,developer_tools,phone_voip_call_state,web_rdp_connection,compromised,Hour,target
17736894,9,37,4,14,29856000.0,0.0,-1,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,10,1
17736895,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2176,0,0,-1,0,11,1
17736917,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2176,0,0,-1,0,9,1
17736926,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2176,0,0,-1,0,11,1
17736945,14,31,4,15,7992800.0,0.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2176,0,0,-1,0,16,1
17736950,14,36,4,15,422592.0,0.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2176,0,0,-1,0,16,1
17739037,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,10,1080x2060,0,0,-1,0,15,1
17739039,10,43,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,13,720x1436,0,1,-1,0,15,1
17742654,8,86,4,15,2090340.0,0.0,-1,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,0,14,1
17749028,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,12,720x1411,1,0,-1,0,16,1


In [49]:
train_part1["browser_language"].loc[train_part1["target"] == 1].unique()

array([-1, 'not available'], dtype=object)

In [50]:
train_part1["browser_language"].loc[train_part1["target"] == 0].unique()

array([-1, 'not available',
       ':not available,iframed:false,intip:2abb1272-fbd8-4d35-897d-b0ee3e862cfd.local,battery:0%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.772588722239781,2.833213344056216,5.484960471420001,3.38368026142383,1.3704421636579194]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:1920,1080,availableScreenResolution:1920,1040,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Adobe Acrobat,Adobe PDF Plug-In For Firefox and Netscape 24.5.20399,application/pdf,pdf,application/vnd.adobe.pdfxml,pdfxml,application/vnd.adobe.x-mars,mars,application/vnd.fdf,fdf,application/vnd.

In [47]:
train_part1["accept_language"].loc[train_part1["target"] == 1].unique()

array([-1, 'ru', '*', 'ru-ru', 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
       'en-GB,en;q=0.9', 'ru-ua',
       'ru,uk-UA;q=0.9,uk;q=0.8,en-US;q=0.7,en;q=0.6', 'ru,en;q=0.9',
       'uk-ua', 'ru-us', 'fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3',
       'be-BY,be;q=0.9,en-US;q=0.8,en;q=0.7',
       'ru-RU,ru;q=0.9,ka-GE;q=0.8,ka;q=0.7,en-US;q=0.6,en;q=0.5',
       'en-US,en;q=0.9', 'en-us', 'en-gb',
       'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'az-az',
       'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7', 'ru,en;q=0.9,tg;q=0.8',
       'ja', 'tr-TR,tr;q=0.9', 'zh-tw',
       'pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6,fi;q=0.5'],
      dtype=object)

In [48]:
train_part1["accept_language"].loc[train_part1["target"] == 0].unique()

array([-1, 'ru-ru', 'ru', 'ru,en;q=0.9',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7', '*',
       'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7',
       'ru,uk-UA;q=0.9,uk;q=0.8,en-US;q=0.7,en;q=0.6', 'en-GB,en;q=0.9',
       'en-gb', 'ru-RU,ru;q=0.9,en-us;q=0.8,en;q=0.7',
       'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'ru-RU,ru;q=0.9',
       'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,fi;q=0.6', 'en,ru;q=0.9',
       'en', 'ru,en-US;q=0.7,en;q=0.3', 'en-us', 'ru-RU',
       'ru,en;q=0.9,de;q=0.8', 'ru,ru-RU;q=0.9,en-US;q=0.8,en;q=0.7',
       'ru-RU,ru;q=0.9,en-IN;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru,en;q=0.9,uk;q=0.8',
       'ru-RU,ru;q=0.9,el-CY;q=0.8,el;q=0.7,en-US;q=0.6,en;q=0.5',
       'en-US,en;q=0.9',
       'ru-RU,ru;q=0.9,en-IN;q=0.8,en;q=0.7,en-US;q=0.6',
       'ru-RU,ru;q=0.9,en-AS;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru-RU,ru;q=0.9,en-AU;q=0.8,en;q=0.7,en-US;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,bg;q=0.6,es;q=0.5', 'ru-ua',
       'tr-tr',
       'ru-RU,ru;q=0.9,es-RU

In [42]:
train_part1["timezone"].loc[train_part1["target"] == 1].unique()

array([-1., 28., 31., 13., 14., 20.,  3., 39., 26.,  1., 27., 32., 33.,
       36.,  2.,  0., 18., 21., 16., 23., 17.,  8., 10., 42., 24., 15.,
       47., 38.])

In [44]:
train_part1["timezone"].loc[train_part1["target"] == 0].unique()

array([-1.000e+00,  3.100e+01,  3.800e+01,  2.800e+01,  1.000e+01,
        3.300e+01,  1.600e+01,  8.000e+00,  1.300e+01,  2.700e+01,
        2.600e+01,  2.300e+01,  4.200e+01,  4.000e+01,  7.600e+01,
        8.300e+01,  5.800e+01,  3.200e+01,  4.600e+01,  7.000e+01,
        6.400e+01,  5.700e+01,  7.100e+01,  5.500e+01,  6.500e+01,
        2.000e+01,  3.900e+01,  2.100e+01,  3.000e+00,  1.800e+01,
        0.000e+00,  1.200e+01,  1.400e+01,  9.000e+00,  2.400e+01,
        1.500e+01,  1.900e+01,  2.900e+01,  1.000e+00,  1.100e+01,
        7.000e+00,  2.000e+00,  2.500e+01,  3.600e+01,  9.700e+01,
        5.000e+00,  1.700e+01,  3.500e+01,  4.000e+00,  3.700e+01,
        1.080e+02,  7.900e+01,  6.000e+00,  4.100e+01,  6.700e+01,
        5.000e+01,  4.300e+01,  3.400e+01,  4.400e+01,  3.000e+01,
        4.800e+01,  1.090e+02,  7.300e+01,  9.900e+01,  7.700e+01,
        5.200e+01,  5.900e+01,  6.000e+01,  5.600e+01,  5.088e+03,
        6.600e+01,  4.500e+01,  2.200e+01,  5.300e+01,  8.059e

In [45]:
train_part1["device_system_version"].loc[train_part1["target"] == 1].unique()

array([-1, '13', '12', '16.7.11', '14', '18.4.1', '18.3.1', '10', '11',
       '9', '15', '8.1.0', '18.3.2', '7.0', '17.6.1', '18.3', '18.1.1',
       '18.2.1', '8.0.0', '14.7.1', '16.1.1', '7.1.1', '18.0', '15.3.1',
       '18.1', '16.3.1', '16.4.1', '17.4.1', '17.5.1', '16.7.10', '15.6',
       '7.1.2', '15.8.3', '16.7', '18.4'], dtype=object)

In [46]:
train_part1["device_system_version"].loc[train_part1["target"] == 0].unique()

array([-1, '13', '12', '14', '15', '9', '16.7.10', '11', '16.7.11',
       '18.0', '18.1.1', '18.3.2', '18.4.1', '18.5', '8.1.0', '17.6.1',
       '10', '18.3.1', '18.2', '18.2.1', '16.1.1', '16.6', '18.4', '16.1',
       '18.3', '17.4.1', '15.8.4', '16.2', '17.5.1', '15.8.3', '7.0',
       '15.2.1', '7.1.1', '16.0', '8.0.0', '18.0.1', '15.8', '15.7.9',
       '6.0.1', '18.1', '17.7.1', '16.5.1', '17.3.1', '7.1.2', '16.3.1',
       '17.7', '14.2.1', '17.2.1', '15.1', '15.4.1', '16.7.6', '15.0.2',
       '16.7.8', '16.7', '14.5.1', '17.0.2', '15.6.1', '17.7.2', '17.7.4',
       '17.7.5', '17.6', '17.4', '17.2', '15.5', '14.7.1', '15.8.2',
       '15.4', '14.4.1', '10.0', '16.6.1', '14.8.1', '15.7.3', '15.3.1',
       '16.7.2', '14.4', '16.1.2', '15.0', '17.7.6', '15.6', '17.1.1',
       '17.0.1', '16.4', '17.7.3', '17.7.7', '17.7.8', '17.1', '14.6',
       '16.7.1', '16.0.3', '17.1.2', '15.3', '15.0.1', '16.7.7', '16.5',
       '17.0.3', '17.5', '16.4.1', '16.3', '14.1', '17.3', '15.2',

In [40]:
train_part1["operating_system_type"].loc[train_part1["target"] == 1].unique()

array([-1.,  6.,  4.,  9.,  7.,  2.,  8.,  3.])

In [41]:
train_part1["operating_system_type"].loc[train_part1["target"] == 0].unique()

array([-1.,  6.,  2.,  4.,  8.,  7.,  9.,  3.,  1.,  0., 10.,  5.])

In [38]:
train_part1["battery"].loc[train_part1["target"] == 1].unique()

array([-1, 'not available', '100%', '46%', '28.999999999999996%', '92%',
       '93%', '41%', '40%', '39%', '95%', '83%', '99%', '54%', '52%',
       '48%', '64%', '34%', '22%', '84%', '78%', '38%', '51%', '98%',
       '96%', '32%', '25%', '26%', '21%', '65%', '43%', '5%', '66%',
       '70%', '80%', '47%', '86%', '15%', '90%', '61%', '42%', '94%',
       '67%', '82%', '53%', '57.99999999999999%', '9%', '63%',
       '56.99999999999999%', '12%', '73%', '17%', '45%',
       '7.000000000000001%', '24%', '97%', '71%', '30%',
       '56.00000000000001%', '62%', '68%', '36%', '91%', 'NaN%', '75%',
       '19%', '77%', '72%', '79%', '50%', '89%'], dtype=object)

In [39]:
train_part1["battery"].loc[train_part1["target"] == 0].unique()

array([-1, 'not available', '93%', '100%', '76%', '73%', '69%',
       '55.00000000000001%', '54%', '53%', '61%', '56.00000000000001%',
       '42%', '87%', '51%', '43%', '98%', '59%', '6%', '77%', '99%',
       '80%', '89%', '30%', '96%', '36%', '62%', '72%', '47%', '46%',
       '79%', '82%', '78%', '52%', '22%', '4%', '85%', '49%', '71%',
       '92%', '94%', '97%', '18%', '63%', '81%', '84%', '64%', '39%',
       '66%', '33%', '90%', '28.000000000000004%', '60%', '40%', '32%',
       '20%', '34%', '70%', '38%', '48%', '74%', '86%', '41%', '67%',
       '14.000000000000002%', '57.99999999999999%', '25%', '35%', '50%',
       '95%', '44%', '9%', '17%', '45%', '65%', '68%', '91%', '83%',
       '75%', '12%', '27%', '16%', '28.999999999999996%', '23%', '19%',
       '37%', '21%', '56.99999999999999%', '88%', '26%', '24%', '8%',
       '11%', '10%', '0%', '15%', '31%', '1%', '2%', '5%', '3%', '13%',
       'NaN%', '7.000000000000001%',
       ':0%,User-Agent:Mozilla/5.0 (Windows NT 10.0

In [35]:
train_part1["screen_size"].loc[train_part1["target"] == 1].unique()

array([-1, '1080x2158', '1080x2168', '375x812', '1200x2394', '414x896',
       '1080x2207', '1080x2270', '1080x2122', '1220x2482', '390x844',
       '1080x2242', '720x1393', '1080x2186', '1080x2107', '1080x2177',
       '720x1384', '1080x2194', '1080x2176', '1080x2232', '720x1444',
       '720x1465', '720x1438', '720x1449', '1080x2115', '720x1460',
       '1080x2095', '1440x2723', '1080x2226', '1080x2224', '720x1600',
       '1080x2116', '720x1440', '1080x2170', '720x1280', '1080x2130',
       '1080x2209', '1080x2125', '720x1448', '1080x2153', '1080x2195',
       '1080x2166', '720x1507', '393x852', '1080x2238', '1080x2460',
       '1220x2560', '1080x2360', '720x1411', '1080x2134', '1080x2181',
       '720x1467', '900x1600', '1080x2132', '1080x2173', '720x1477',
       '1220x2712', '1080x2179', '1080x2131', '1080x2098', '1080x2030',
       '1080x2352', '1080x2163', '1080x2161', '540x960', '720x1372',
       '1080x2094', '1440x2730', '1080x2340', '1080x2160', '1080x2189',
       '720x136

In [32]:
train_part1["screen_size"].loc[train_part1["target"] == 0].unique()

array([-1, '1080x2180', '720x1507', ..., '666x1287', '1312x2707',
       '1312x2848'], shape=(1523,), dtype=object)

Получили обработанный набор данных, теперь можно переходить к обучению моделей.

In [ ]:
# train_part1.to_parquet("ClearData/train_part1.parquet", index=False, engine="fastparquet")